import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/components/Providers";

const geistSans = {
	variable: "--font-geist-sans",
	className: "font-sans",
};

const geistMono = {
	variable: "--font-geist-mono",
	className: "font-mono",
};

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
